// Names of the Worker bindings and variables used by the application.

export const SEND_EMAIL_SECTION = "send_email";
export const RATE_LIMIT_SECTION = "ratelimits";

export const SEND_EMAIL_BINDING = "SEND_EMAIL";
export const SEND_EMAIL_RATELIMIT_BINDING = "SEND_EMAIL_RATELIMIT";

export const CONTACT_EMAIL_ADDRESS_BINDING = "CONTACT_EMAIL_ADDRESS";
export const CONTACT_EMAIL_ADDRESS_RATELIMIT_BINDING = "CONTACT_EMAIL_ADDRESS_RATELIMIT";

export const NOTION_TOKEN_BINDING = "NOTION_TOKEN";
export const WAITLIST_DATA_SOURCE_BINDING = "WAITLIST_DATA_SOURCE_ID";
export const WAITLIST_RATELIMIT_BINDING = "WAITLIST_RATELIMIT";

export const RATE_LIMIT_BINDINGS = [
  SEND_EMAIL_RATELIMIT_BINDING,
  CONTACT_EMAIL_ADDRESS_RATELIMIT_BINDING,
  WAITLIST_RATELIMIT_BINDING,
] as const;

export const SECRET_BINDINGS = [
  CONTACT_EMAIL_ADDRESS_BINDING,
  NOTION_TOKEN_BINDING,
  WAITLIST_DATA_SOURCE_BINDING,
] as const;

export type RateLimitBindingName = (typeof RATE_LIMIT_BINDINGS)[number];
export type SecretName = (typeof SECRET_BINDINGS)[number];
