export const SITE_NAME = "kuzmano.ski";
export const SITE_URL = "https://kuzmano.ski";
export const SITE_DESCRIPTION = "Brian's personal website.";
export const SITE_SOURCE_URL = "https://github.com/bkuzmanoski/kuzmano.ski";
export const SOCIAL_IMAGE = "/logo512.png";
export const FEED_MAX_ENTRIES = 20;
export const FEED_ICON = "/logo192.png";
export const FEED_LOGO = "/logo512.png";
export const NOT_FOUND_DOCUMENT_TITLE = "Page not found (404)";
export const CONTENT_SIGNAL = "ai-train=no, search=yes, ai-input=yes";
