/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SegmentIndexRouteImport } from './routes/$segment/index'
import { Route as SegmentSlugRouteImport } from './routes/$segment/$slug'
import { Route as ApiClientErrorsRouteImport } from './routes/api/client-errors'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentIndexRoute = SegmentIndexRouteImport.update({
  id: '/$segment/',
  path: '/$segment/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentSlugRoute = SegmentSlugRouteImport.update({
  id: '/$segment/$slug',
  path: '/$segment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientErrorsRoute = ApiClientErrorsRouteImport.update({
  id: '/api/client-errors',
  path: '/api/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/$segment/$slug': typeof SegmentSlugRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/$segment/': typeof SegmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/$segment/$slug': typeof SegmentSlugRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/$segment': typeof SegmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/$segment/$slug': typeof SegmentSlugRoute
  '/api/client-errors': typeof ApiClientErrorsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/$segment/': typeof SegmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contact'
    | '/$segment/$slug'
    | '/api/client-errors'
    | '/api/contact'
    | '/api/waitlist'
    | '/$segment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contact'
    | '/$segment/$slug'
    | '/api/client-errors'
    | '/api/contact'
    | '/api/waitlist'
    | '/$segment'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contact'
    | '/$segment/$slug'
    | '/api/client-errors'
    | '/api/contact'
    | '/api/waitlist'
    | '/$segment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContactRoute: typeof ContactRoute
  SegmentSlugRoute: typeof SegmentSlugRoute
  ApiClientErrorsRoute: typeof ApiClientErrorsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  SegmentIndexRoute: typeof SegmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$segment/': {
      id: '/$segment/'
      path: '/$segment'
      fullPath: '/$segment/'
      preLoaderRoute: typeof SegmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$segment/$slug': {
      id: '/$segment/$slug'
      path: '/$segment/$slug'
      fullPath: '/$segment/$slug'
      preLoaderRoute: typeof SegmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-errors': {
      id: '/api/client-errors'
      path: '/api/client-errors'
      fullPath: '/api/client-errors'
      preLoaderRoute: typeof ApiClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContactRoute: ContactRoute,
  SegmentSlugRoute: SegmentSlugRoute,
  ApiClientErrorsRoute: ApiClientErrorsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  SegmentIndexRoute: SegmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
