/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegmentIndexRouteImport } from './routes/$segment/index'
import { Route as SegmentSlugRouteImport } from './routes/$segment/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentIndexRoute = SegmentIndexRouteImport.update({
  id: '/$segment/',
  path: '/$segment/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentSlugRoute = SegmentSlugRouteImport.update({
  id: '/$segment/$slug',
  path: '/$segment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$segment/$slug': typeof SegmentSlugRoute
  '/$segment/': typeof SegmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$segment/$slug': typeof SegmentSlugRoute
  '/$segment': typeof SegmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$segment/$slug': typeof SegmentSlugRoute
  '/$segment/': typeof SegmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$segment/$slug' | '/$segment/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$segment/$slug' | '/$segment'
  id: '__root__' | '/' | '/$segment/$slug' | '/$segment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SegmentSlugRoute: typeof SegmentSlugRoute
  SegmentIndexRoute: typeof SegmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$segment/': {
      id: '/$segment/'
      path: '/$segment'
      fullPath: '/$segment/'
      preLoaderRoute: typeof SegmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$segment/$slug': {
      id: '/$segment/$slug'
      path: '/$segment/$slug'
      fullPath: '/$segment/$slug'
      preLoaderRoute: typeof SegmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SegmentSlugRoute: SegmentSlugRoute,
  SegmentIndexRoute: SegmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
